# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('citizenship', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('locations', models.TextField()),
                ('difficulty', models.CharField(choices=[('1', 'Very Easy'), ('2', 'Easy'), ('3', 'Average'), ('4', 'Difficult'), ('5', 'Very Difficult')], max_length=5)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('U', 'Unsuccessful'), ('S', 'Successful')], max_length=5)),
                ('comments', models.TextField()),
                ('heroID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.Hero')),
                ('missionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.Mission')),
                ('teamID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='heroes.Team')),
            ],
        ),
    ]
