# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('gender', models.CharField(default=b'Please Add Gender', max_length=15)),
                ('address', models.TextField()),
                ('citizenship', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('locations', models.TextField()),
                ('difficulty', models.CharField(choices=[(b'1', b'Very Easy'), (b'2', b'Easy'), (b'3', b'Average'), (b'4', b'Difficult'), (b'5', b'Very Difficult')], max_length=5)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[(b'U', b'Unsuccessful'), (b'S', b'Successful')], max_length=5)),
                ('comments', models.TextField()),
                ('heroID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.Hero')),
                ('missionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.Mission')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.Hero')),
                ('missionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='missions.Mission')),
                ('teamID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='heroes.Team')),
            ],
        ),
    ]
