# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='Please Add Gender', max_length=15),
        ),
        migrations.AlterField(
            model_name='mission',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Very Easy'), ('2', 'Easy'), ('3', 'Average'), ('4', 'Difficult'), ('5', 'Very Difficult')], max_length=5),
        ),
        migrations.AlterField(
            model_name='report',
            name='outcome',
            field=models.CharField(choices=[('U', 'Unsuccessful'), ('S', 'Successful')], max_length=5),
        ),
    ]
