# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='Please Add Gender', max_length=15),
        ),
    ]
