# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='teamID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='heroes.Team'),
        ),
    ]
