# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('occupation', models.CharField(max_length=30)),
                ('citizenship', models.CharField(max_length=40)),
                ('species', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=30)),
                ('profilePic', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('powers', models.CharField(choices=[('1', 'Extremely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Average'), ('5', 'Good'), ('6', 'Above Average'), ('7', 'High'), ('8', 'Very High'), ('9', 'Super Human'), ('10', 'Above and Beyond')], max_length=5)),
                ('intelligence', models.CharField(choices=[('1', 'Extremely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Average'), ('5', 'Good'), ('6', 'Above Average'), ('7', 'High'), ('8', 'Very High'), ('9', 'Super Human'), ('10', 'Above and Beyond')], max_length=5)),
                ('durability', models.CharField(choices=[('1', 'Extremely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Average'), ('5', 'Good'), ('6', 'Above Average'), ('7', 'High'), ('8', 'Very High'), ('9', 'Super Human'), ('10', 'Above and Beyond')], max_length=5)),
                ('strength', models.CharField(choices=[('1', 'Extremely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Average'), ('5', 'Good'), ('6', 'Above Average'), ('7', 'High'), ('8', 'Very High'), ('9', 'Super Human'), ('10', 'Above and Beyond')], max_length=5)),
                ('speed', models.CharField(choices=[('1', 'Extremely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Average'), ('5', 'Good'), ('6', 'Above Average'), ('7', 'High'), ('8', 'Very High'), ('9', 'Super Human'), ('10', 'Above and Beyond')], max_length=5)),
                ('heroID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.Hero')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.Hero')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='alias',
            name='heroID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.Hero'),
        ),
    ]
