# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('formerCodeNames', models.TextField(default=b'Please Add Former Codenames', max_length=25)),
                ('occupation', models.CharField(max_length=30)),
                ('address', models.TextField(default=b'Please Add Address')),
                ('citizenship', models.CharField(max_length=40)),
                ('species', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=30)),
                ('profilePic', models.ImageField(blank=True, upload_to=b'')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('powers', models.TextField(default=b'Please add powers')),
                ('intelligence', models.CharField(choices=[(b'1', b'Extremely Low'), (b'2', b'Very Low'), (b'3', b'Low'), (b'4', b'Average'), (b'5', b'Good'), (b'6', b'Above Average'), (b'7', b'High'), (b'8', b'Very High'), (b'9', b'Super Human'), (b'10', b'Above and Beyond')], max_length=5)),
                ('durability', models.CharField(choices=[(b'1', b'Extremely Low'), (b'2', b'Very Low'), (b'3', b'Low'), (b'4', b'Average'), (b'5', b'Good'), (b'6', b'Above Average'), (b'7', b'High'), (b'8', b'Very High'), (b'9', b'Super Human'), (b'10', b'Above and Beyond')], max_length=5)),
                ('strength', models.CharField(choices=[(b'1', b'Extremely Low'), (b'2', b'Very Low'), (b'3', b'Low'), (b'4', b'Average'), (b'5', b'Good'), (b'6', b'Above Average'), (b'7', b'High'), (b'8', b'Very High'), (b'9', b'Super Human'), (b'10', b'Above and Beyond')], max_length=5)),
                ('speed', models.CharField(choices=[(b'1', b'Extremely Low'), (b'2', b'Very Low'), (b'3', b'Low'), (b'4', b'Average'), (b'5', b'Good'), (b'6', b'Above Average'), (b'7', b'High'), (b'8', b'Very High'), (b'9', b'Super Human'), (b'10', b'Above and Beyond')], max_length=5)),
                ('heroID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.Hero')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('leader', models.CharField(max_length=25)),
                ('address', models.TextField(default=b'Please Add Address')),
                ('description', models.TextField(default=b'Please Add Description')),
                ('members', models.TextField(default=b'Please Add Members')),
            ],
        ),
        migrations.AddField(
            model_name='alias',
            name='heroID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.Hero'),
        ),
    ]
