# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='address',
            field=models.TextField(default='Please Add Address'),
        ),
        migrations.AlterField(
            model_name='alias',
            name='formerCodeNames',
            field=models.TextField(default='Please Add Former Codenames', max_length=25),
        ),
        migrations.AlterField(
            model_name='hero',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stats',
            name='durability',
            field=models.CharField(choices=[('1', 'Extremely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Average'), ('5', 'Good'), ('6', 'Above Average'), ('7', 'High'), ('8', 'Very High'), ('9', 'Super Human'), ('10', 'Above and Beyond')], max_length=5),
        ),
        migrations.AlterField(
            model_name='stats',
            name='intelligence',
            field=models.CharField(choices=[('1', 'Extremely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Average'), ('5', 'Good'), ('6', 'Above Average'), ('7', 'High'), ('8', 'Very High'), ('9', 'Super Human'), ('10', 'Above and Beyond')], max_length=5),
        ),
        migrations.AlterField(
            model_name='stats',
            name='powers',
            field=models.TextField(default='Please add powers'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='speed',
            field=models.CharField(choices=[('1', 'Extremely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Average'), ('5', 'Good'), ('6', 'Above Average'), ('7', 'High'), ('8', 'Very High'), ('9', 'Super Human'), ('10', 'Above and Beyond')], max_length=5),
        ),
        migrations.AlterField(
            model_name='stats',
            name='strength',
            field=models.CharField(choices=[('1', 'Extremely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Average'), ('5', 'Good'), ('6', 'Above Average'), ('7', 'High'), ('8', 'Very High'), ('9', 'Super Human'), ('10', 'Above and Beyond')], max_length=5),
        ),
        migrations.AlterField(
            model_name='team',
            name='address',
            field=models.TextField(default='Please Add Address'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(default='Please Add Description'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.TextField(default='Please Add Members'),
        ),
    ]
