# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='address',
            field=models.TextField(default='Please Add Address'),
        ),
        migrations.AddField(
            model_name='alias',
            name='formerCodeNames',
            field=models.TextField(default='Please Add Former Codenames', max_length=25),
        ),
        migrations.AddField(
            model_name='status',
            name='TeamID',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='status',
            name='missionID',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='team',
            name='address',
            field=models.TextField(default='Please Add Address'),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(default='Please Add Description'),
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.TextField(default='Please Add Members'),
        ),
    ]
