# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_auto_20170110_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.CharField(max_length=25),
        ),
    ]
