# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0005_auto_20170112_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='TeamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.Team'),
        ),
    ]
