# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0006_auto_20170112_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='TeamID',
        ),
        migrations.AddField(
            model_name='status',
            name='teamID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='heroes.Team'),
        ),
        migrations.AlterField(
            model_name='status',
            name='missionID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='missions.Mission'),
        ),
    ]
