# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtraining',
            name='description',
            field=models.TextField(default='Please Add Description'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='address',
            field=models.TextField(default='Please Add Address'),
        ),
    ]
