# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20170110_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='endTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
