# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20170117_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='date',
            new_name='classDate',
        ),
    ]
